### ISSUE TITLE
Release 0.2 Checklist

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#1063]
- [x] CLI tests on all commands but not on Kafka - @fmassot 
- [x] CLI tests with Kafka source - @fulmicoton 
- [x] Merge doc page on Storage URI - @fulmicoton 
- [x] Merge doc page on Metastore configuration - @fulmicoton 
- [x] Check and merge Architecture doc page - @fulmicoton 
- [x] Check and merge Introduction doc page - @fulmicoton 
- [x] Update website docs - @fmassot
- [x] Create tag v0.2.0 (it will publish the binaries)
- [x] Redirect  https://install.quickwit.io/ to https://raw.githubusercontent.com/quickwit-inc/quickwit/v0.2.0/install.sh
- [x] Publish blog post
- [x] Publish on twitter, reddit, hackernews, linkedin
